### ISSUE TITLE
Tests break with alpha version of Test::More

### ISSUE THREAD

**Issue by exodist** [chiselwright/test-dbix-class-schema#12]
https://github.com/Test-More/test-more/issues/481

It looks like your test file lists a failed test from 'done_testing', your comments around it indicate it should not and that you are hacking around a bug. In the latest alpha version of Test::More this extra result does not occur. This is good news cause it fixes the bug, but is bad news cause it breaks your modules test suite.

The easy fix would be to check if $INC{'Test/Stream.pm'} is set, if it is do not add the extra result.

**Comment by eserte** [comment]
1.0.9 (still? again?) is broken with the latest Test::More devel releases (more specifically with Test-Simple-1.302014_003). Failing test output starts with:
```
#   Failed test 'test output as expected for passing case'
#   at t/40.untested.columns.t line 74.
# STDOUT is:
#   ok 1 - use UnexpectedTest::Schema;
#   ok 2 - An object of class 'UnexpectedTest::Schema' isa 'UnexpectedTest::Schema'
#   ok 3 - The record object is a ::SpanishInquisition
#   ok 4 - 'id' column defined in result_source
#   ok 5 - 'id' column exists in database
#   ok 6 - 'name' column defined in result_source
#   ok 7 - 'name' column exists in database
#   ok 8 # skip no relations methods
#   ok 9 # skip no custom methods
#   ok 10 # skip no resultsets methods
# > not ok 11 - planned to run 4 but done_testing() expects 10
# not:
#   ok 1 - use UnexpectedTest::Schema;
#   ok 2 - An object of class 'UnexpectedTest::Schema' isa 'UnexpectedTest::Schema'
#   ok 3 - The record object is a ::SpanishInquisition
#   ok 4 - 'id' column defined in result_source
#   ok 5 - 'id' column exists in database
#   ok 6 - 'name' column defined in result_source
#   ok 7 - 'name' column exists in database
#   ok 8 # skip no relations methods
#   ok 9 # skip no custom methods
#   ok 10 # skip no resultsets methods
# > 
# as expected
```

**Comment by chiselwright** [comment]
Pushed to CPAN a few minutes ago as 1.0.10

**Comment by exodist** [comment]
https://github.com/Test-More/test-more/issues/667  this may interest you, related to the 'wtf' you have in your code in regards to planning.
